### PR TITLE
Wrap invocation recording in a mutex

### LINKED ISSUE #41: Race condition when calling different methods in parallel
I am seeing a race condition sporadically when calling different methods in parallel. It only happens when different methods are called, since calling the same method in parallel leads to the method mutex being invoked, and preventing race conditions.

An example test case (nested within the existing **when two methods are called at the same time** describe block):

```
		It("records its calls without race conditions", func(done Done) {
			go fake.DoNothing()
			go fake.DoThings("abc", 1)
			go fake.DoASlice([]byte{})

			Eventually(len(fake.Invocations()["DoNothing"]), 1.0).Should(Equal(1))
			Eventually(len(fake.Invocations()["DoThings"]), 1.0).Should(Equal(1))
			Eventually(len(fake.Invocations()["DoASlice"]), 1.0).Should(Equal(1))

			close(done)
		})
```
Leads to output like:
```
WARNING: DATA RACE
Write by goroutine 17:
  github.com/maxbrunsfeld/counterfeiter/fixtures/fixturesfakes.(*FakeSomething).DoThings()
      /Users/bazza/go/src/github.com/maxbrunsfeld/counterfeiter/fixtures/fixturesfakes/fake_something.go:43 +0x297

Previous read by goroutine 15:
  github.com/maxbrunsfeld/counterfeiter_test.glob.func1.14.2()
      /Users/bazza/go/src/github.com/maxbrunsfeld/counterfeiter/counterfeiter_test.go:195 +0x197
```
(and a lot more redacted for the sake of brevity)

Attempting to sleuth a little, it seems like this was probably a result of trying to record invocations. The counterfeit method for **DoASlice** for instance looks like this:
```
func (fake *FakeSomething) DoASlice(arg1 []byte) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.doASliceMutex.Lock()
	fake.doASliceArgsForCall = append(fake.doASliceArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	fake.guard("DoASlice")
	fake.invocations["DoASlice"] = append(fake.invocations["DoASlice"], []interface{}{arg1Copy})
	fake.doASliceMutex.Unlock()
	if fake.DoASliceStub != nil {
		fake.DoASliceStub(arg1)
	}
}
```
Note that there is a mutex for the specific **DoASlice** method, but **not** for the call to `fake.guard` and `fake.invocations["DoASlice"]` which both mutate the `fake.invocations` field. If calls were made to multiple methods on the same fake, they would both mutate the `fake.invocations` field at the same time.

Unfortunately I can't get the test case to be 100% deterministic, since one goroutine might complete before the other starts. However, running 3 methods in parallel (as in the above test case) seems to be more consistent than just 2.

### PR DESCRIPTION
**Pull request by Burr**
* Prevents writing to invocations map from different methods
* Test case to show that invocations can be recorded in parallel
* Changes to expected results to include new mutex & recording method
* fixes #41 

At a high level, here is the change:
* Rather than calling `guard` and then updating the `invocations` map, it calls a new `recordInvocation` method, which does the guard/invocations update, wrapped in a mutex.
* `guard` method is removed since the functionality has been moved into `recordInvocation`

### CODE REVIEW

**Comment by Burr** [comment]
To be honest, I'm not convinced the problem is totally solved with this change - there may still be an issue with it. Right now the new test case is verifying with the statements:

```
			Eventually(fake.DoNothingCallCount, 1.0).Should(Equal(1))
			Eventually(fake.DoThingsCallCount, 1.0).Should(Equal(1))
			Eventually(fake.DoASliceCallCount, 1.0).Should(Equal(1))
```

This works....unless you switch it to read from the `Invocations`, like so:

```
			Eventually(len(fake.Invocations()["DoNothing"]), 1.0).Should(Equal(1))
			Eventually(len(fake.Invocations()["DoThings"]), 1.0).Should(Equal(1))
			Eventually(len(fake.Invocations()["DoASlice"]), 1.0).Should(Equal(1))
```

At that point you may get race conditions again. I believe this is a result of the fact that you are **reading** the Invocations in the test while at the same time you might still be **writing** them from other goroutines being processed. So you might be in a situation where you have to know to only verify calls via the `CallCount` methods rather than the `Invocations` method (at least if you want to do things in parallel). That doesn't seem ideal.

It does still fix the initial problem - previously even trying to use the `CallCount` methods while running things in parallel caused a problem. So it is better, it just may not be completely fixed.

I spent a little bit of time trying to figure out alternative ways to handle it. The only thing I could think of was to not have an `invocations` map at all as a field on the fake, and to just create a new `map` on each call to `Invocations`. That would be a little ugly, though, since you'd need to do a `RLock` on every single `<methodName>Mutex` and then append them all to the new map by name.

Anyway, any feedback is definitely welcome - I'd like to fix this in an ideal way, and I'm not sure this is it. Any ideas/alternatives would be appreciated.

**Comment by tjarratt** [comment]
Hmm, thanks for opening up this PR @Burr. I hadn't thought too much about the need for handling race conditions here, but that's definitely a feature of Counterfeiter, and something worth maintaining. I really appreciate the time and energy you spent here.

Seems like we should grab the write read lock in the `Invocations() map[string][]interface{}` function, otherwise there will be an inherent race condition in the case you mentioned. If I get a free moment, I'll try that out and see if it makes that case pass under the `-race` flag.

**Comment by tjarratt** [comment]
Just merged your commit and added another to address the issue you raised about the interplay between calling `fake.MySpecialFunc()` and calling `fake.Invocations()` across goroutines.

Does this address what you set out to fix, @Burr?

**Comment by Burr** [comment]
Yep, all looks great to me. Not sure why I didn't think of putting in a full mutex call in the `Invocations`, thanks for adding that.

Thanks @maxbrunsfeld and @tjarratt ,  much appreciated (both for the help on the PR, and the library in general)

**Comment by tjarratt** [comment]
Thanks! I get a great joy from working with (and on counterfeiter). It makes me feel good knowing that the work I've done helps other people be more effective when writing tests. 

Glad I could be of assistance :)

Sent From A Very Small Keyboard

**Pull request merged**
