### PR TITLE
Interactive mode

### PR DESCRIPTION
**Pull request by tjarratt**
This pull request adds a few happy commits.

Interactive Mode
=============

You can provide counterfeiter with a single argument, a path to a file or directory, and counterfeiter will inspect the containing package for all exported interface types and interactively prompt the user for the interface they wanted.

If stdin doesn't appear to be a TTY, then counterfeiter cowardly refuses to prompt the user. My intention here is that we should play nicely with scripts and tools so that existing users aren't burned by this change.

Integration tests
============

I felt like the existing test suite, while nice, lacked some testing of behavior in main. In addition to breaking some functionality out of `main()`, I wanted some integration tests to verify the behavior that existed in counterfeiter prior to this pull request, especially since I was <strike>changing</strike>amending the public interface.

Less Code in `main`()
=================

Main was getting rather clunky, and I'd like to extract more functionality into separate packages where appropriate, so that individual components are easier to test.

I'm not convinced that the "argument parser" package is perfect, given that it's also writing to STDIO and reading from STDIN, but moving code out of `main` is a big win in my book.

### CODE REVIEW

**Comment by tjarratt** [comment]
Is it worth amending this PR to include vendoring dependencies with `godep`, so that the last commit is more semantically meaningful, rather than the rather vague "fix script that I broke as part of this work" ?

Or would that be better as a separate PR once this is merged?

**Comment by tjarratt** [comment]
Hey @maxbrunsfeld any thoughts on this? Would love to get this merged in so I can tackle some of the outstanding bugs with dot imports and name collisions in imported packages.

**Comment by maxbrunsfeld** [comment]
Hey, really sorry for letting this hang out for 3 weeks @tjarratt. I haven't been coding go much, as you can probably tell, so it took me a little time to read and understand everything that you did here. Look legit to me!

**Comment by maxbrunsfeld** [comment]
:raised_hands: :key: :raised_hands:

**Comment by tjarratt** [comment]
Thanks Max. It's a real honor to get to work on a tool that provides as much utility as Counterfeiter.

**Pull request merged**
