### PR TITLE
Address races when using Returns and ReturnsOnCall, and make the behavior of ReturnsOnCall be less annoying.

### PR DESCRIPTION
**Pull request by jimgrier**
1. Although there is an RWMutex in the mocking structure, it is used inconsistently, leading to the Go race detector to cause sporadic data race errors while unit testing.

2. The ...ReturnsOnCall() method allows for the creation of a map such that one may specify return values on arbitrary calls to the mocked function. For example, you can request that the first two invocations fail, followed by a successful call, in order to check out retry behavior. The problem is that once this map is set, the default return value for the mocked function call becomes all nils and not what was intended. This led to situations where it was necessary to call the mocked function first and save the returns, then set the map values for failures to one offset from the desired index, and set ANY indices that might be hit other to the saved default value. This violates the Principle of Least Surprise.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
https://github.com/maxbrunsfeld/counterfeiter/releases/tag/v6.0.0 does away with the use of `ast` for code generation. Is this still an issue?

**Comment by joefitzgerald** [comment]
@jimgrier could you articulate in more detail what you mean by item 2 in your description, above?

**Comment by joefitzgerald** [comment]
I am going to close this as fixed, and suggest that we think about item 2 from the description separately.

**Comment by miroslavLalev** [comment]
Hey, are there any updates in regards to item 2 here? I still see that the default stub is set to `nil` when calling any `ReturnsOnCall` function.

**Pull request closed without merging**
