### PR TITLE
Handle generic params and return types

### PR DESCRIPTION
**Pull request by Ralph7C2**
This only covers the case where the interface itself isn't generic but accepts or returns a generic with a concrete type arg.

Currently, the fake fails to import the package for the type arg. Now, while creating imports, we iterate over TypeArgs for named types and import the packages for them.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Thanks for this! I will take a detailed look in the next day, but at first glance it looks great 🙏

**Comment by Ralph7C2** [comment]
Hey @joefitzgerald I'd like to resurrect this if I could, I just bumped into this problem again. https://goplay.tools/snippet/cRLlU7yek6Q is a summary

The problem could _also_ be fixed if concrete types fulfilled interfaces with interfaces int heir methods (a mouthful, I know). But, that seems less likely and I _think_ this patch would fix the issue for me(allowing to generate a fake for the specified generic in an interface)

**Comment by joefitzgerald** [comment]
Hey @Ralph7C2 sorry for the delay. Looking at this now.

**Comment by joefitzgerald** [comment]
@Ralph7C2, sorry for the lengthy delay in getting this merged (work [got a little crazy](https://www.reuters.com/markets/deals/broadcom-closes-69-bln-vmware-deal-after-china-approval-2023-11-22/#:~:text=Nov%2022%20(Reuters)%20%2D%20Broadcom,ending%20a%20months%2Dlong%20saga.)). Thanks for the contribution!

Hi @zachgersh! It's great to hear from you!! You can always feel free to be that person 😄 ❤️.

**Pull request merged**
