### PR TITLE
Added new mode (-p)

### PR DESCRIPTION
**Pull request by lwoydziak**
Package mode:  When invoked in package mode, counterfeiter
will generate an interface and shim implementation from a
package in your GOPATH.  Counterfeiter finds the public
methods in the package <source-path> and adds those method
signatures to the generated interface <interface-name>.

Signed-off-by: Luke Woydziak <luke.woydziak@emc.com>

### CODE REVIEW

**Comment by tjarratt** [comment]
Haven't forgot about this. I need to get this rebased on top of `master` to take into account some of the changes that @challiwill made recently.

**Comment by tjarratt** [comment]
Thank you so much for the amazing patience you've shown me while I've dragged my feet merging this PR @lwoydziak.

**Comment by tjarratt** [comment]
Merged this manually, it should be on master as `c2f4a41282ca1e8652d0b534450f021380b1bf39`.

It was a pretty gnarly rebase, but all of the tests pass, and I could still run

`counterfeiter -p os` in order to generate an "osshim", which is pretty rad.

**Comment by lwoydziak** [comment]
@tjarratt I know you are extremely busy so thank you very much!

Also check out: 
https://github.com/cloudfoundry-incubator/goshims
Which has many already done for you :)

**Pull request closed without merging**
